### ISSUE TITLE
KISS

### ISSUE THREAD

**Issue by aaloy** [python-spain/empresas#1]
No tiene sentido que para incribirte en una lista de empresas tengas que hacer un PR.

**Comment by quobit** [comment]
Entiendo que te puede parecer excesivo. Estamos hablando de empresas de software, por otro lado.
Incluiré una lista de pasos en [CONTRIBUTING.md](../blob/master/.github/CONTRIBUTING.md) para principiantes (cuyo único requisito es tener una cuenta en GitHub).

Con respecto a la información que se pretende recoger de cada empresa ¿te parece poca? ¿mucha?

**Comment by quobit** [comment]
He añadido una lista de pasos en [CONTRIBUTING.md](../blob/master/.github/CONTRIBUTING.md#pasos-para-incluir-una-empresa)  @aaloy
