### ISSUE TITLE
Dargo no parece existir

### ISSUE THREAD

**Issue by n3storm** [python-spain/empresas#22]
El dominio ha caducado en  6/12/2018 según godaddy (que no sé que fecha es, si el 12 de este mes o en el futuro mes de enero)

La cuenta Github tampoco se encuentra.

Sugiero que antes de que el enlace lleve a algún sitio con spam,malware,etc se elimine la entrada de Dargo.

**Comment by quobit** [comment]
Gracias por el aviso @n3storm! :cake:
