### ISSUE TITLE
Sugerencia de nuevo criterio de *python-friendliness*

### ISSUE THREAD

**Issue by Mariagil** [python-spain/empresas#24]
*Saludos. Se me ocurre que otro buen criterio para acreditar la python-friendliness podría ser si la empresa y/o sus trabajadores contribuyen a la comunidad Python mejorando o creando código.  Muchas gracias.

**Comment by astrojuanlu** [comment]
O si, como parte de su jornada, publican código o colaboran con proyectos ya existentes. Buena idea!

**Comment by quobit** [comment]
Retocaré los criterios y avisaré a todos para que revisen su _python friendliness_

**Comment by Mariagil** [comment]
Estupendo, muchas gracias por aceptar la propuesta. Feliz miércoles.

**Comment by quobit** [comment]
Actualizada la lista de criterios con aportaciones a la comunidad.

Aviso a todos para que revisen y actualicen la cantidad de pitones si cumplen el nuevo criterio:

@cayetanobv @axenedu @costular @n3storm @mzaforas @migonzalvar @merqurio @jsmanrique @diegosuarez @XaviTorello @Mariagil @tapia @tanrax @fmrtn @ecarreras @danigm @amatellanes @Xevib @RDCH106

**Comment by diegosuarez** [comment]
Gracias por el aviso, de momento nos quedamos en 3 serpientes (con intención de ir a por la cuarta).

Creo que debería actualizarse el README.md para reflejarlo, no? 
@quobit te ocupas, o hago un pull request? :)

**Comment by quobit** [comment]
Tienes razón! Gracias. Ya lo corrijo.

**Comment by RDCH106** [comment]
Actualizo de acuerdo lo mencionado en https://github.com/python-spain/empresas/issues/28#issuecomment-538386860
