### ISSUE TITLE
Revision de sitios

### ISSUE THREAD

**Issue by n3storm** [python-spain/empresas#28]
Suena a que quiero desacerme de competidores pero no es así :) No da buena imagen enlazar a sitios rotos y/o susceptibles de ser secuestrados y atacar a los visitantes.

- https://wadobo.com/ 502, sin actividad en twiter desde 2018
- https://ingran.es/ Certificado ssl caducado desde 2018
- initios.com El dominio no resuelve, sin actividad tuiter desde enero 2019

**Comment by quobit** [comment]
Muchas gracias por avisar @n3storm ! Lo reviso y corrijo.

**Comment by RDCH106** [comment]
El software que antes se realizaba en 🐍 Python y se liberaba, ahora se recoge en el ☂️ paraguas de [Talaikide](https://www.talaikide.com/es_ES/)

Incluyo a Talaikide como sucesor de Ingran 😎
